# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

language: python
git:
  depth: false
env:
  - PRE_COMMIT_HOME=$HOME/.cache/pre-commit
virtualenv:
  system_site_packages: false
jobs:
  fast_finish: true
  include:
    - python: 3.6
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="true"
    - python: 3.7
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py37" COVERAGE="false"
    - python: 3.8
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py38" COVERAGE="false"
    - python: 3.9
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py39" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.8" COVERAGE="false"
    - stage: deploy
      script: skip
      deploy:
        edge: true
        provider: pypi
        username: willu47
        password:
          secure: b+jIvSEU2My0Bpgsv0/tZqbmZsrLPEOkLymxu5uCOWFfaLk8ALSW+R+J3xRJkB02UYOqYuf5E0tXMeAEzM5weCLgJ42kB+AeXrdDXU2n7Fkm61SimTz50wzpv3WenhRMW0A9CqFJHS7kQY7gGcRGcBbDnqg9yssnay8visCNYNGCskiKAwvJjv7mrill2/pJVpautqbvtZRJ3+AeV9UEJSvP88TvHH8lC5p/MnzhebO4IZ8C6MymIUXaKqfQAtpM2Co+ftlMEcHktRx4jUmd1SGQci8A86sITTsUDwQzWJrbR8RiqaUfasCl3gtdL3QQty1lkvoHEzDRVV9512q2qRsjEvbP0p3cFjjXrzZXA8URGrhFyh2Kdm/kvPw6J3yi0OgHtnnoRHRAQuYhGnJ4CGYDtoTSyBMmx7rPzyG1pYcFvUH8MxGOSo0wcfUKAmmWAhxHNmVvTvlBbdlm1A+Z1s0dVU1ePVEmUKacXVaq72f3nUjHAfa6tteVE6MOig6ljXcpuZRnnCJZlT9WEFtMGgMfNJBeWSVO0XXXR+tn1bJw5kDMO6quqKHAGCIWI2uZCBdroCMCrmXjc7upAmy3NhnbuHAudTRRXTPCoWssyu5hOkMfnobJBXDM+7KIwhWbFHQnuP2la7S1r9FrAnN2Rn/B0n1stGLX7UGqUgsuDac=
        on:
          tags: true
          all_branches: false
        cleanup: false
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "wusher@kth.com"
  - git config --global user.name "Will Usher"
  # Useful information in case of debug
  - if [[ "$DISTRIB" == "conda" ]]; then conda info -a; fi
  - which tox
script:
  - tox -e build
  - tox
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
    - $HOME/.cache/pre-commit
notifications:
  email: false
